### ISSUE TITLE
Interested in porting this tool to Linux

### ISSUE THREAD

**Issue by abhas** [Wilba6582/zeal60#3]
I wanted to check if you can provide any simple directions or starting points to port / rebuild this tool for Linux.

Thanks a lot!

**Comment by devBrouwer** [comment]
see: https://github.com/Wilba6582/zeal60/pull/1
It's already working for me for quite some time :)

**Comment by wilba** [comment]
Yes, sorry I have not pulled this yet, I was going to set up Linux and try it first.

**Comment by wilba** [comment]
The code now compiles under Linux. Be sure to update to the latest firmware, available from ZealPC.net

https://zealpc.net/blogs/news/programming-your-zeal60-rgb-pcb

or build the zeal60 branch of my QMK fork:

https://github.com/Wilba6582/qmk_firmware/tree/zeal60
