### ISSUE TITLE
LED colours & reactive lighting

### ISSUE THREAD

**Issue by garethellis36** [Wilba6582/zeal60#5]
Hello,

I built my Zeal60 yesterday and I'm having fun using it so far.

Is there a way I can find out the HSV values for the lights I have on the keyboard right now? Whenever I re-flash the keyboard it sets the colours back to the default in the batch file. I've figured out how to change the default effect, but I've no idea what the colour codes are for what I've got. I'm only changing the hue using FN3+4 until I get to the right colour - does increment hue change the starting hue value by a certain amount each time, e.g. 10-20?

Also, I've seen reference to reactive LED mode but I can't see anywhere how I can enable that. Please advise. Thank you for a great product and firmware!

**Comment by garethellis36** [comment]
I worked out the former by counting the number of increments (32) and dividing 360 by that number - each hue increment adds that resulting number to the hue value. 

Still stuck on the reactive mode though.

**Comment by wilba** [comment]
Effect #5 has a "reactive mode", keys that are pressed will be shifted in hue and return back to the same hue as the rest of the keys after a while.

I'm working on a better app for setting colors (and keymaps) using the PC... I totally agree that setting colors by HSV values is hard and not user-friendly.
